cmake_minimum_required(VERSION 3.10)
project(ap)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include_directories(include /home/amin/raylib/header) 
link_directories(/home/amin/raylib/build)
include_directories(/usr/include/SFML)
add_executable(app src/main.cpp src/programm.cpp)
target_link_libraries(app raylib     sfml-graphics     sfml-window     sfml-system)
