@startuml Horrified_Board_Game_Class_Diagram

!theme plain
skinparam classAttributeIconSize 0
skinparam classFontSize 10
skinparam classFontName Arial
skinparam packageFontSize 12
skinparam packageFontName Arial-Bold

' Main Game Controller
class programm {
  + static constexpr int maxn = 10000
  + int night_terror = 0
  + std::vector<location *> list_of_location
  + std::vector<item *> list_of_items
  + std::vector<perk *> list_of_perks
  + std::vector<std::vector<int>> my_map
  + std::vector<monster *> monster_list
  + std::vector<monster_card *> monster_card_list
  + std::vector<hero *> hero_list
  + std::vector<int> vec = {15, 13, 3, 4, 9}
  --
  + perk *set_award(int)
  + void next_frenzy()
  + std::vector<int> bfs(int s, int t)
  + int get_night_terror()
  + void set_night_terror(int)
  + bool check_terro_night()
  + void run(bool)
  + programm()
  + ~programm()
  + void save_game(const std::string file_name, std::vector<int>&)
  + void load_game(std::string)
}

' Abstract Base Classes
abstract class hero {
  # location *loc
  # int action
  # std::vector<item *> item_have
  # std::vector<perk *> perk_have
  # std::string name_of_hero
  --
  + {abstract} void special_action(std::vector<std::vector<int>> &map, programm &bug, sf::RenderWindow &window)
  + void advance(std::vector<monster *> &monsters, programm &bug, sf::RenderWindow &window, std::vector<int>&)
  + void guide(std::vector<std::vector<int>> &map, programm &, sf::RenderWindow &window, programm &bug)
  + void defeat(std::vector<monster *> &monsters, programm &bug, sf::RenderWindow &window)
  + void move(location *loc, programm &bug)
  + int get_action()
  + void set_perks(std::vector<perk *> perks)
  + std::vector<perk *> &get_perks()
  + void set_item(std::vector<item *> items)
  + std::vector<item *> &get_items()
  + void pickup(sf::RenderWindow &window, programm &bug)
  + void set_action(int)
  + location *get_loc()
  + std::string get_hero_name()
  + hero(std::vector<perk *> &)
  + void use_perk(programm &, sf::RenderWindow &window)
  + void save_game(const std::string)
  + void load_game(std::string, programm &bug)
  + void ability(std::string, sf::RenderWindow &window)
  + ~hero()
}

abstract class monster {
  # bool is_freenzy
  # int freenzy_order
  # location *loc
  # std::string name_of_monster
  # int totla_hidden_item
  # bool did_attack = false
  --
  + {abstract} void ability(programm &bug)
  + bool get_freenzy_status()
  + void move_to_place(std::vector<int> &route, int number_route, programm &bug)
  + void set_loc(location *)
  + location *get_loc()
  + bool get_is_frenzy()
  + int get_frenzy_order()
  + void set_is_frenzy(bool)
  + void set_frenzy_order(int)
  + std::string get_mons_name()
  + int &get_hidden_item()
  + bool get_did_attack()
  + void set_did_attack(bool did_attack)
  + void save_game(const std::string)
  + void load_game(std::string, programm &)
  + ~monster()
}

abstract class perk {
  + std::string name
  --
  + std::string get_name()
  + {abstract} void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + perk()
  + virtual ~perk()
  + void save_game(const std::string)
  + void load_game(std::string, programm &)
}

abstract class monster_card {
  # int item_count
  # int dice_play
  # int move_left
  # std::string name_of_card
  --
  + {abstract} void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void _strike(int dice_attack, int move, programm &bug, monster *monsters)
  + {abstract} void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void item_handler(programm &help_object)
  + int get_item_count()
  + int get_dice_play()
  + int get_move_count()
  + virtual ~monster_card()
  + void save_game(const std::string)
  + void load_game(std::string, programm&)
  + std::string getName()
}

' Location and Map
class location {
  - int loc_relation
  - bool coffin_exist
  - std::vector<villager *> villager_list
  - std::vector<item *> item_list
  - std::vector<hero *> hero_list
  - std::vector<monster *> monster_list
  --
  + void set_coffin_exist(bool)
  + void set_villager(villager *)
  + void set_loc_relation(int)
  + void set_item_list(item *)
  + void set_hero_list(hero *)
  + void set_monster_list(monster *)
  + int get_loc_relation() const
  + bool get_coffin_exist() const
  + std::vector<villager *> &get_villager_list()
  + std::vector<item *> &get_item_list()
  + std::vector<hero *> &get_hero_list()
  + std::vector<monster *> &get_monster_list()
  + location(int relation, bool coffin)
  + void delete_item()
  + void delete_villager_list()
  + void delete_monster_list()
  + ~location()
  + void save_game(std::string)
  + void load_game(std::string, programm &)
}

enum map1 {
  hospital = 0
  grave_yard = 1
  church = 2
  institute = 3
  laboratory = 4
  shop = 5
  museum = 6
  cryptt = 7
  abbey = 8
  mansion = 9
  theatre = 10
  tower = 11
  docks = 12
  inn = 13
  precinct = 14
  barn = 15
  dungeon = 16
  cave = 17
  camp = 18
}

' Item and Color System
class item {
  - int power
  - std::string name
  - rgb::Color color
  - location *loc
  --
  + item(int, std::string, rgb::Color, location *)
  + int get_power()
  + std::string get_name()
  + rgb::Color get_Color()
  + location *get_loc()
  + void set_power(int)
  + ~item()
  + void save_game(const std::string)
  + void load_game(std::string, programm &)
}

namespace rgb {
  enum Color {
    Red
    Blue
    Yellow
  }
}

' Villager System
class villager {
  - std::string name
  - location *safe_location
  - location *current_location
  - perk *award
  --
  + void set_name(std::string)
  + void set_current_location(location *)
  + villager(std::string, location *, location *, programm &help_object)
  + ~villager()
  + location *get_currnet_location()
  + location *const get_safe_location()
  + perk *drop_the_perk()
  + std::string get_name()
  + void save_game(const std::string)
  + void load_game(std::string, programm &)
  + void set_award(perk *)
}

' Hero Implementations (CORRECTED - only 4 actual heroes)
class Archaeologist {
  --
  + void special_action(std::vector<std::vector<int>> &map, programm &bug, sf::RenderWindow &window)
  + Archaeologist(int, location *, std::vector<perk *> &)
}

class scientist {
  --
  + void special_action(std::vector<std::vector<int>> &map, programm &bug, sf::RenderWindow &window)
  + scientist(int, location *, std::vector<perk *> &)
}

class courier {
  --
  + void special_action(std::vector<std::vector<int>> &map, programm &bug, sf::RenderWindow &window)
  + courier(int, location *, std::vector<perk *> &)
}

class Mayor {
  --
  + void special_action(std::vector<std::vector<int>> &map, programm &bug, sf::RenderWindow &window)
  + Mayor(int, location *, std::vector<perk *> &)
}

' Monster Implementations
class Drakula {
  --
  + void ability(programm &bug)
  + Drakula(int coffin, bool is_freenzy, int freenzy_order, location *ptr)
}

' Monster Card Implementations (CORRECTED - these are NOT heroes!)
class Thief {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Thief(int dic, int my_item, int mover)
}

class The_Innocent {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + The_Innocent(int dic, int my_item, int mover)
}

class The_Delivery {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + The_Delivery(int dic, int my_item, int mover)
}

class The_chthyologist {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + The_chthyologist(int dic, int my_item, int mover)
}

class Sunrise {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Sunrise(int dic, int my_item, int mover)
}

class On_the_move {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + On_the_move(int dic, int my_item, int mover)
}

class Hypnotic_Gaze {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Hypnotic_Gaze(int dic, int my_item, int mover)
}

class Hurried_Assistant {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Hurried_Assistant(int dic, int my_item, int mover)
}

class Fortune_Teller {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Fortune_Teller(int dic, int my_item, int mover)
}

class Former_Employer {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Former_Employer(int, int, int mover)
}

class form_of_the_bat {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + int get_item()
  + form_of_the_bat(int dic, int my_item, int mover)
}

class Egyptian_Expert {
  --
  + void event(std::vector<std::vector<int>> &map, std::vector<location *> &loc, programm &a)
  + void monster_strike(programm &bug, std::vector<monster *> &monsters)
  + void set_item(int item_count)
  + Egyptian_Expert(int dic, int my_item, int mover)
}

' Perk Implementations
class repel {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + repel()
  + ~repel()
}

class hurry {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + hurry()
  + ~hurry()
}

class visit_from_detective {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + visit_from_detective()
  + ~visit_from_detective()
}

class overstock {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + overstock()
  + ~overstock()
}

class late_into_night {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + late_into_night()
  + ~late_into_night()
}

class break_of_down {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + break_of_down()
  + ~break_of_down()
}

class massage {
  --
  + void play(programm &help_obj1, sf::RenderWindow &window, hero *her=nullptr)
  + massage()
  + ~massage()
}

' UI Components
class Button {
  - sf::RectangleShape shape
  - sf::Font font
  - sf::Text label
  - sf::Vector2f position
  --
  + Button(const sf::Vector2f& size, const sf::Vector2f& position, const std::string& text)
  + void draw(sf::RenderWindow& window)
  + bool isClicked(const sf::Event& event, const sf::RenderWindow& window)
  + sf::Vector2f getPosButton()
}

class Button2 {
  - sf::RectangleShape shape
  - sf::Font font
  - sf::Text label
  - sf::Vector2f position
  --
  + Button2(const sf::Vector2f& size, const sf::Vector2f& position, const std::string& text)
  + void draw(sf::RenderWindow& window)
  + bool isClicked(const sf::Event& event, const sf::RenderWindow& window)
  + sf::Vector2f getPosButton()
}

class TextInputBox {
  - sf::RectangleShape box
  - sf::Text text
  - sf::Font font
  - std::string input
  - bool isActive
  --
  + TextInputBox(sf::Vector2f position, sf::Vector2f size)
  + void handleEvent(const sf::Event& event, const sf::RenderWindow& window)
  + void draw(sf::RenderWindow& window, std::string massage)
  + std::string getInput() const
  + void clear()
  + sf::Vector2f getPos()
}

' Menu System
class Menu {
  - std::vector<sf::Text> buttons
  - int hovered_index
  --
  + int run()
}

class LoadGameMenu {
  - std::string clickedButton
  - sf::RenderWindow window
  --
  + LoadGameMenu()
  + std::string run()
}

class HintMenu {
  --
  + int run()
}

' Utility Functions
class free_func {
  --
  + int showLocationTextBox(sf::RenderWindow &window, programm &bug, hero &herr)
  + void showCenteredTextBox(sf::RenderWindow &window, const std::string &text)
  + void showAssetInBox(sf::RenderWindow &window, const std::string &directory, const std::string &assetName)
  + std::string showTextInputBox(sf::RenderWindow &window, const std::string &prompt)
  + int extractNumber(const std::string &pathStr)
  + std::string showHerovillagerBox(sf::RenderWindow &window, int loc_selec, programm &bug)
  + std::string showHeroPerksBox(sf::RenderWindow &window, hero *heroPtr)
  + std::string showHeroitemBox(sf::RenderWindow &window, int loc_selec, programm &bug)
  + std::string show_hero_on_location(sf::RenderWindow &window, programm &bug)
  + int show_all_location(sf::RenderWindow &window, programm &bug)
  + int show_monster_location(sf::RenderWindow &window, programm &bug, monster* monn)
  + void playSound(std::string SoundDir)
  + std::string show_hero_item_have(sf::RenderWindow &window, hero *heroPtr)
  + std::string show_monster_asset(sf::RenderWindow &window, const std::string &monster_folder_path)
  + std::string show_folder_save(sf::RenderWindow &window)
  + void load_game_hero(std::string file_name, programm &bug)
  + void save_game_state(std::vector<int>&, std::string, programm &bug)
  + void load_game_state(std::string file_name, programm &bug)
}

' CORRECTED Inheritance Relationships
hero <|-- Archaeologist
hero <|-- scientist
hero <|-- courier
hero <|-- Mayor

monster <|-- Drakula

perk <|-- repel
perk <|-- hurry
perk <|-- visit_from_detective
perk <|-- overstock
perk <|-- late_into_night
perk <|-- break_of_down
perk <|-- massage

monster_card <|-- Thief
monster_card <|-- The_Innocent
monster_card <|-- The_Delivery
monster_card <|-- The_chthyologist
monster_card <|-- Sunrise
monster_card <|-- On_the_move
monster_card <|-- Hypnotic_Gaze
monster_card <|-- Hurried_Assistant
monster_card <|-- Fortune_Teller
monster_card <|-- Former_Employer
monster_card <|-- form_of_the_bat
monster_card <|-- Egyptian_Expert

' Associations
programm ||--o{ location : "manages"
programm ||--o{ item : "contains"
programm ||--o{ perk : "provides"
programm ||--o{ monster : "controls"
programm ||--o{ monster_card : "uses"
programm ||--o{ hero : "manages"

hero ||--o{ location : "occupies"
hero ||--o{ item : "carries"
hero ||--o{ perk : "has"
hero ||--o{ programm : "interacts with"

monster ||--o{ location : "occupies"
monster ||--o{ programm : "controlled by"

location ||--o{ villager : "contains"
location ||--o{ item : "contains"
location ||--o{ hero : "contains"
location ||--o{ monster : "contains"

villager ||--o{ location : "located in"
villager ||--o{ perk : "drops"

item ||--o{ location : "found in"
item ||--o{ rgb::Color : "has color"

monster_card ||--o{ programm : "affects"

' UI Associations
Menu ||--o{ Button : "contains"
LoadGameMenu ||--o{ Button : "contains"
HintMenu ||--o{ Button : "contains"

' Notes
note top of programm : "Main Game Controller\nManages game state, monsters, heroes, and locations"
note top of hero : "Abstract base class for all playable characters\nOnly 4 actual hero implementations"
note top of monster : "Abstract base class for all enemy entities\nMonsters have AI behavior and frenzy states"
note top of location : "Represents game board locations\nContains items, NPCs, heroes, and monsters"
note top of perk : "Abstract base class for special abilities\nPerks provide strategic advantages to heroes"
note top of monster_card : "Abstract base class for monster action cards\nControls monster behavior and events\nMany classes I initially thought were heroes are actually monster cards!"

note right of map1 : "Enumeration of all game locations\nUsed for navigation and positioning"

@enduml 